apps/alumno/urls.py
from django.conf.urls import include, url
from apps.alumno.views import index, alumno_view, alumno_list, alumno_edit, alumno_delete, \
	AlumnoList, AlumnoCreate, AlumnoUpdate, AlumnoDelete

urlpatterns = [
    # Examples:
    url(r'^$', index, name ='index'),
    url(r'^nuevo$', AlumnoCreate.as_view(), name='alumno_crear'),
    url(r'^listar$', AlumnoList.as_view(), name='alumno_listar'),
    url(r'^editar/(?P<pk>\d+)/$', AlumnoUpdate.as_view(), name='alumno_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', AlumnoDelete.as_view(), name='alumno_eliminar'),
]

apps/maestros/urls.py
from django.conf.urls import include, url
from apps.maestros.views import index_maestros

urlpatterns = [
   url(r'^index$',index_maestros),
]

sea/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login

urlpatterns = [
    # Examples:
    # url(r'^$', 'sea.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^alumno/', include('apps.alumno.urls', namespace="alumno")),
    url(r'^maestros/', include('apps.maestros.urls', namespace="maestros")),
    url(r'^$', login,{'template_name':'index.html'},name='login')

]

apps/alumno/models.py
from django.db import models

# Create your models here.
class sexo(models.Model):
	sexo =models.CharField(max_length=10)

	def __str__(self):
		return self.sexo

class alumno(models.Model):
	Identidad=models.CharField(max_length=15)
	nombres =models.CharField(max_length=50)
	apellidos =models.CharField(max_length=50)
	fechaNac = models.DateField()
	sexo =models.ForeignKey(sexo, null=True, blank=True, on_delete=models.CASCADE)

	def __str__(self):
		return '{} {} {}'.format(self.Identidad, self.nombres, self.apellidos)

apps/maestros/models.py
from django.db import models

from apps.alumno.models import sexo

class maestros(models.Model):
	Identidad=models.CharField(max_length=15)
	nombres =models.CharField(max_length=50)
	apellidos =models.CharField(max_length=50)
	fechaNac = models.DateField()
	sexo =models.ForeignKey(sexo, null=True, blank=True, on_delete=models.CASCADE)

# Create your models here.

apps/alumno/forms.py
from django import forms
from apps.alumno.models import alumno

class AlumnoForm(forms.ModelForm):

	class Meta:
			model = alumno

			fields = [
				'Identidad',
				'nombres',
				'apellidos',
				'fechaNac',
				'sexo',
			]
			labels = {
				'Identidad': 'identidad',
				'nombres': 'nombres', 
				'apellidos': 'apellidos',
				'fechaNac': 'Fecha de Nacimiento',
				'sexo':'sexo',
			}
			widgets = {
				'Identidad':forms.TextInput(attrs={'class':'form-control'}),
				'nombres':forms.TextInput(attrs={'class':'form-control'}),
				'apellidos':forms.TextInput(attrs={'class':'form-control'}),
				'fechaNac':forms.TextInput(attrs={'class':'form-control'}),
				'sexo': forms.Select(attrs={'class':'form-control'}),
			}


			

apps/alumno/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.alumno.forms import AlumnoForm
from apps.alumno.models import alumno


def index(request):
	return render(request, 'alumno/index.html')

def alumno_view(request):
	if request.method == 'POST':
		form = AlumnoForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('alumno:index')
	else:
		form = AlumnoForm()
	return render(request, 'alumno/alumnos_form.html',{'form':form})	

def alumno_list(request):
	alumnos = alumno.objects.all()
	contexto = {'alumnos':alumnos}
	return render(request,'alumno/alumno_list.html',contexto)

def alumno_edit(request, id_alumno):
	alumnos = alumno.objects.get(id=id_alumno)
	if request.method=='GET':
		form = AlumnoForm(instance=alumnos)
	else:
		form= AlumnoForm(request.POST,instance=alumnos)
		if form.is_valid():
			form.save()
		return redirect('alumno:alumno_listar')
	return render(request, 'alumno/alumnos_form.html',{'form':form})

def alumno_delete(request, id_alumno):
	alumnos = alumno.objects.get(id=id_alumno)
	if request.method =='POST':
		alumnos.delete()
		return redirect('alumno:alumno_listar')
	return render(request, 'alumno/alumno_delete.html',{'alumno':alumno})



# listas basada es clases

class AlumnoList(ListView):
	model = alumno
	template_name ='alumno/alumno_list.html'

class AlumnoCreate(CreateView):
	model = alumno
	form_class=AlumnoForm
	template_name ='alumno/alumnos_form.html'
	success_url=reverse_lazy('alumno:alumno_listar')

class AlumnoUpdate(UpdateView):
	model = alumno
	form_class=AlumnoForm
	template_name ='alumno/alumnos_form.html'
	success_url=reverse_lazy('alumno:alumno_listar')

class AlumnoDelete(DeleteView):
	model = alumno
	template_name ='alumno/alumno_delete.html'
	success_url=reverse_lazy('alumno:alumno_listar')

apps/maestros/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index_maestros (request):
	return HttpResponse("Soy la pagina principal de la pagina maestros")

templates/alumno/alumno_delete.html
{% extends 'base/base.html' %}

{% block content %}

	<form method="post">
		{% csrf_token %}
		<h3>Desea eliminar el registro de {{ object.nombres }}</h3>
		<button class="btn btn-danger" type="submit">Si, Eliminar</button>
		<a class="btn btn-primary" href="{% url 'alumno:alumno_listar'  %}">Cancelar</a>
		

	</form>

{% endblock %}

templates/alumno/alumno_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>LISTADO DE ALUMNOS</h1>
<table class="table table-bordered">
	<thead>	
		<tr>
			<td>#</td>
			<td>Identidad</td>
			<td>Nombres</td>
			<td>Apellidos</td>
			<td>Fecha de Nacimiento</td>
			<td>Sexo</td>
			<td>Acciones</td>
		</tr>
	</thead>	
	<tbody>
		{% if object_list %}
		{% for alumno in object_list %}
		<tr>
			<td> {{alumno.id}} </td>
			<td> {{alumno.Identidad}} </td>
			<td> {{alumno.nombres}} </td>
			<td> {{alumno.apellidos}} </td>
			<td> {{alumno.fechaNac}} </td>
			<td> {{alumno.sexo}} </td>
			<td>
				<a class="btn btn-primary" href="{% url 'alumno:alumno_editar' alumno.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'alumno:alumno_eliminar' alumno.id %}">Elimnar</a>
			</td>
		</tr>
		{%endfor%}
		{% else %}
		<h1>No hay Registros</h1>
		{% endif %}


	</tbody>


</table>

{% endblock %}

templates/alumno/alumnos_form.html
{% extends 'base/base.html' %}

{% block content %}

	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">guardar</button>

	</form>

{% endblock %}

templates/alumno/index.html
{%extends 'base/base.html'%}
<title>{% block title %}App Alumno {%endblock%}</title>

	{%block content%}
		<a class="btn btn-primary" href="{% url 'alumno:alumno_listar'  %}">Editar</a>
	{%endblock%}

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	
	{%block static %}
		<meta charset="UTF-8">
		<link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
		<link rel="stylesheet" href="{% static 'css/estilo_index_login.css'%}">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	{%endblock%}
<title>
{% block title %}Document {%endblock%}
</title>

</head>
<body>
	{% block header%}
	{% block navbar %}
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		  		<a class="navbar-brand" href="#">SEA</a>
		  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
		    		<span class="navbar-toggler-icon"></span>
		  		</button>

		  		<li class="nav-item dropdown">
	              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Flatly <span class="caret"></span></a>
	              <div class="dropdown-menu" aria-labelledby="download">
	                <a class="dropdown-item" href="https://jsfiddle.net/bootswatch/jmg3gykg/">Open in JSFiddle</a>
	                <div class="dropdown-divider"></div>
	                <a class="dropdown-item" href="../4/flatly/bootstrap.min.css">bootstrap.min.css</a>
	                <a class="dropdown-item" href="../4/flatly/bootstrap.css">bootstrap.css</a>
	                <div class="dropdown-divider"></div>
	                <a class="dropdown-item" href="../4/flatly/_variables.scss">_variables.scss</a>
	                <a class="dropdown-item" href="../4/flatly/_bootswatch.scss">_bootswatch.scss</a>
	              </div>
	            </li>
		  	</nav>
	{% endblock %}
	{%endblock%}
	{% block content%}
	{%endblock%}
	<script src="{% static 'js/jquery.min.js' %}"> </script>
	<script src="{% static 'js/jquery-3.1.1.min.js' %}"> </script>
	<script src="{% static 'js/bootstrap.min.js' %}"> </script>
</body>
</html>

templates/base/header.html
<header>Hola</header>

templates/index.html
{% extends 'base/base.html' %}
{% block title %}
sea
{% endblock %}
{% block navbar %}

{% endblock %}

{% block content %}

<form method="post" class="login" >
	{% csrf_token %}
		<h3 class="text-center">Bienvenidos a SEA</h3>
		<div class="form-group">
			<label for="Nombre">Nombre</label>
			<input type="text" class="form-control" name="username" id="Nombre" placeholder="Escribe tu nombre">
    	</div>

    	<div class="form-group">
			<label for="Pass">Contraseña:</label>
			<input type="password" class="form-control" name="password" id="Pass" placeholder="Escribe tu Clave">
		</div>
<p class="text-center">
	<input class="btn btn-primary" type="submit" value="Ingresar">
			
		</p>
</form>


{% endblock %}